### ISSUE TITLE
Script doesn't work in Safari

### ISSUE THREAD

**Issue by Cakeday** [gnat/css-scope-inline#3]
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

See also: https://stackoverflow.com/questions/72776199/react-application-on-safari-throws-syntaxerror-invalid-regular-expression-inva

Invalid regular expression: invalid group specifier name

Safari doesn't support RegEx lookbehind (?<=), meaning this is app-breaking for Safari users.:

```javascript
node.textContent = node.textContent.replace(
      /(^|\.|(?<=\s|[^a-zA-Z0-9\-\_]))(me|this|self)(?![a-zA-Z])/g,
      "." + scope
    ); // Can use: me this self
```

**Comment by gnat** [comment]
For readers from the future: [Safari 16.4 and later are unaffected](https://caniuse.com/js-regexp-lookbehind)

As for us right now: I've come up with a higher performance version of the existing regex, that **does not include the negative lookbehind**. This bug report will actually turn out to be a performance win.

It will be in the next update.
